train: 
  initial_environment: 'pickles/Oxford/Oxford_train_queries.pickle'
  incremental_environments: ['pickles/In-house/In-house_train_queries.pickle', 'pickles/Wuhan/whu_campus_origin_train_queries.pickle', 'pickles/Wuhan/wh_hankou_origin_train_queries.pickle']
eval:
  environments: {
    'Oxford': {
      'stage_introduced': 0,
      'database_files': ['pickles/Oxford/Oxford_evaluation_database.pickle'],
      'query_files': ['pickles/Oxford/Oxford_evaluation_query.pickle'],
    },
    'In-house': {
      'stage_introduced': 1,
      'database_files': ['pickles/In-house/university_evaluation_database.pickle','pickles/In-house/residential_evaluation_database.pickle','pickles/In-house/business_evaluation_database.pickle'],
      'query_files': ['pickles/In-house/university_evaluation_query.pickle','pickles/In-house/residential_evaluation_query.pickle','pickles/In-house/business_evaluation_query.pickle'],
    },
    'WHU-Campus': {
      'stage_introduced': 2,
      'database_files': ['pickles/Wuhan/whu_campus_origin_evaluation_database.pickle'],
      'query_files': ['pickles/Wuhan/whu_campus_origin_evaluation_query.pickle'],
    },
    'Hankou': {
      'stage_introduced': 3,
      'database_files': ['pickles/Wuhan/wh_hankou_origin_evaluation_database.pickle'],
      'query_files': ['pickles/Wuhan/wh_hankou_origin_evaluation_query.pickle'],
    },
  }
  world_thresh: {
    'Oxford': 25,
    'DCC': 10,
    'Riverside': 10,
    'In-house': 25,
    'Hankou': 30,
    'WHU-Campus': 30
  }
  false_pos_thresh: {
    'Oxford': -1,
    'DCC': 20,
    'Riverside': 20,
    'In-house': -1,
    'Hankou': -1,
    'WHU-Campus': -1
  }
  time_thresh: {
    'Oxford': -1,
    'DCC': 90,
    'Riverside': 90,
    'In-house': -1,
    'Hankou': -1,
    'WHU-Campus': -1
  }